# Welcome message when a player joins the server
welcome_message: "Welcome %playername%~"
# Round end message
round_end_info: "Round ended! Don't leave, see you in the next roundヾ(￣▽￣)~"
# Friendly fire enabled message
f_f_message: "<align=center> <color=#F6511D> ~Friendly fire enabled~ </color></align>"
# Auto server message text
auto_server_message_text: "Welcome to the server, have fun!"
# Chat message list title
chat_message_title: "Message list:"
# Names of different message types
message_type_name:
  AdminPrivateChat: "Admin private chat"
  BroadcastChat: "Public message"
  TeamChat: "Team message"
# Custom player role names in chat
chat_system_role_translation:
  ClassD: "Class D personnel"
  FacilityGuard: "Guard"
  ChaosConscript: "Chaos Conscript"
  ChaosMarauder: "Chaos Marauder"
  ChaosRepressor: "Chaos Repressor"
  ChaosRifleman: "Chaos Rifleman"
  NtfCaptain: "NTF Captain"
  NtfPrivate: "NTF Private"
  NtfSergeant: "NTF Sergeant"
  NtfSpecialist: "NTF Specialist"
  Scientist: "Scientist"
  Tutorial: "Tutorial character"
  Scp096: "SCP-096"
  Scp049: "SCP-049"
  Scp173: "SCP-173"
  Scp939: "SCP-939"
  Scp079: "SCP-079"
  Scp0492: "SCP-049-2"
  Scp106: "SCP-106"
  Scp3114: "SCP-3114"
  Spectator: "Spectator"
  Overwatch: "Overwatch"
  Filmmaker: "Filmmaker"
# Custom team names in chat
chat_system_team_translation:
  Dead: "Dead"
  ClassD: "Class D"
  OtherAlive: "Mysterious team"
  Scientists: "Scientists"
  SCPs: "SCP"
  ChaosInsurgency: "Insurgents"
  FoundationForces: "MTF"
# Admin log
admin_log: "%Nickname% at %Time% | Used command: %Command% | Steam64ID: %UserId%"
# Admin log broadcast
admin_log_broadcast: "<size=30>[<color=red>Admin action logs</color>] <%Nickname%> just used the command: %Command%</size>"
# Display remaining time and server status
title_text: "<size=50><color=#F0FF00><b>Waiting for players, {seconds}</b></color></size>"
# Player count display text
player_count_text: "<size=40><color=#FFA600><i>{players}</i></color></size>"
# Server pause message
server_pause_text: "<size=30>Server paused</size>"
# Second line message
second_left_text: "Remaining {seconds}"
# Multiline message
seconds_left_text: "Remaining {seconds}"
# Round start message
round_start_text: "Round start"
# Message when one player joins
player_join_text: "Player joined"
# Message when multiple players join
players_join_text: "players joined"
# Guard mutiny warning
guard_mutiny_broadcast: "<size=60><color=#ff0000ff>[Warning]</color> Guards have mutinied and joined the Chaos"
# Elite guard notification
elite_guard_broadcast: "<size=60><color=#00ffffff>[Notification]</color> Guards this round are an elite MTF unit, they are reinforced."
# Watch list title
watch_list_title: "<align=right><size=45%><color=(COLOR)><b>Observers ((COUNT)):</b></color></size></align>"
# Watch list format
names: "<align=right><size=45%><color=(COLOR)><br>(NAME)</color></size></align>"
# DNT warning
d_n_t_warning: "You have DNT enabled, disable it for plugins to work properly"
# SCP-073 damage reflection reason
s_c_p073_damage_reason: "SCP-073 damage reflection"
# SCP-029 escape message
s_c_p029_escape_hint: "You managed to escape and join the Chaos"
# SCP-703 escape message
s_c_p703_escape_hint: "You managed to escape and become an MTF specialist"
# CASSIE MTF Skynet
skynet_cassie: "Mobile Task Forces Kappa-10 and Mu-7, codenamed Skynet, have entered the facility, supporting the containment of SCP-079. Remaining SCPs: %SCPNum%."
# MTF Skynet skill description
skynet_skill_introduction:
- "You are [MTF Skynet Member] Take care of your light"
- "Generators you activate <color=red>activate quickly</color>"
# MTF Skynet new member welcome
skynet_private_broadcast: "<size=70><color=#0051FF>You are a new member of MTF Skynet</color></size>"
skynet_private_custom_info: "Private Skynet"
# MTF Skynet sergeant welcome
skynet_sergeant_broadcast: "<size=70><color=#0051FF>You are a sergeant of MTF Skynet</color></size>"
skynet_sergeant_custom_info: "Sergeant Skynet"
# MTF Skynet captain welcome
skynet_captain_broadcast: "<size=70><color=#0051FF>You are a captain of MTF Skynet</color></size>"
skynet_captain_custom_info: "Captain Skynet"
# CASSIE MTF Eta-10
see_no_evil_cassie: "Mobile Task Force Eta-10, codenamed See No Evil, has entered the facility, supporting the containment of SCP-096. Remaining SCPs: %SCPNum%."
# MTF Eta-10 skill description
see_no_evil_skill_introduction:
- "You are [MTF Eta-10 Member] - You can look at SCP-096"
- "<color=red>It's hard</color> for him to kill you unless he goes berserk"
# MTF Eta-10 new member welcome
see_no_evil_private_broadcast: "<size=70><color=#0051FF>You are a new member of MTF Eta-10</color></size>"
see_no_evil_private_custom_info: "Private Eta-10"
# MTF Eta-10 sergeant welcome
see_no_evil_sergeant_broadcast: "<size=70><color=#0051FF>You are a sergeant of MTF Eta-10</color></size>"
see_no_evil_sergeant_custom_info: "Sergeant Eta-10"
# MTF Eta-10 captain welcome
see_no_evil_captain_broadcast: "<size=70><color=#0051FF>You are a captain of MTF Eta-10</color></size>"
see_no_evil_captain_custom_info: "Captain Eta-10"
# CASSIE Info suffix
special_role_contain_cassie: "Has been successfully contained"
# Chaos leader role name
chaos_leader_role_name: "Chaos Leader"
# Chaos leader spawn broadcast
chaos_leader_spawn_broadcast: "<size=80><color=#00ff00ff>You are the Chaos Leader</color></size>"
# Chaos leader death CASSIE
chaos_leader_death_cassie: "The Chaos Leader has died"
# SCP-2936-1 spawn broadcast
s_c_p29361_spawn_broadcast: "<size=70>You are <color=red>SCP-2936-1 Giant German Robot</color></size>"
# SCP-2936-1 skill description
s_c_p29361_skill_introduction: "You are [SCP-2936-1] You have a huge body and a lot of health"
# SCP-073 Abel broadcast
s_c_p073_abel_spawn_broadcast: "You are <color=green>SCP-073 Abel</color>"
# SCP-073 Abel skill description
s_c_p073_abel_skill_introduction: "You are [SCP-073] You reflect <color=red>some damage</color> to enemies"
# SCP-073 Cain broadcast
s_c_p073_cain_spawn_broadcast: "You are <color=green>SCP-073 Cain</color>"
# SCP-073 Cain skill description
s_c_p073_cain_skill_introduction: "You are [SCP-073] You have <color=red>infinite</color> regeneration, rest for a while"
# SCP-703 broadcast
s_c_p703_spawn_broadcast: "<size=80><color=#00ffffff>You are SCP-703</color></size>"
# SCP-703 skill description
s_c_p703_skill_introduction:
- "You are [SCP-703] You receive a random item from time to time"
- "Time until the next item <color=red>%Time%</color>"
# SCP-703 received item message
s_c_p703_received_item_hint: "You received an item"
# SCP-029 broadcast
s_c_p029_spawn_broadcast: "<size=60><color=#ff0000ff>You are SCP-029 'Daughter of Shadows'</color></size>"
# SCP-029 skill description
s_c_p029_skill_introduction: "You are [SCP-029] You run at <color=red>tremendous</color> speed"
# SCP-347 broadcast
s_c_p347_spawn_broadcast: "You are <color=red>SCP-347 Invisible Woman</color>"
# SCP-347 skill description
s_c_p347_skill_introduction: "You are [SCP-347] You are <color=red>always</color> invisible, move carefully"
# SCP-1093 broadcast
s_c_p1093_spawn_broadcast: "You are <color=yellow>SCP-1093 Lamp Man</color>"
# SCP-1093 skill description
s_c_p1093_skill_introduction:
- "You are [SCP-1093] You illuminate an area within a 5-meter radius and radiate within a 1-meter radius"
- "Your head is empty, you cannot take head damage"
# Guard captain broadcast
guard_captain_spawn_broadcast: "<size=60><color=#E5DADA>You are the guard captain</color></size>"
# SCP-191 broadcast
s_c_p191_spawn_broadcast: "You have become <color=red>SCP-191 Mechanical Girl</color>"
# SCP-191 skill description
s_c_p191_skill_introduction:
- "You are [SCP-191] Your body has been modified"
- "You have <color=red>high resistance</color> to non-electromagnetic and non-explosive damage"
- "Don't forget to recharge in SCP-079's room"
# SCP-191 battery display
s_c_p191_battery_hint_show: "<align=right><size=40><b>You currently have <color=yellow>%Battery% amps</color> of battery</size></b></align>"
# SCP-191 battery depletion death reason
s_c_p191_battery_depletion_death_reason: "You died from battery depletion"
# SCP-1056 pickup message
s_c_p1056_pickup_hint: "You picked up <color=red>SCP-1056</color> Shrinker!"
# SCP-1056 used message
s_c_p1056_used_hint: "boom! You shrunk!!!"
# SCP-1068 pickup message
s_c_p1068_pickup_hint: "You picked up <color=red>SCP-1068</color> Harmless Atomic Bomb!"
# SCP-1068 used broadcast
s_c_p1068_used_broadcast: "Someone used <color=red>SCP-1068</color> Harmless Atomic Bomb!"
# Special SCP descriptions
s_c_p029_special_introduction: "<color=red>SCP-029 Daughter of Shadows</color>"
s_c_p703_special_introduction: "<color=blue>SCP-703 In the Closet</color>"
s_c_p347_special_introduction: "<color=red>SCP-347 Invisible Woman</color>"
s_c_p1093_special_introduction: "<color=yellow>SCP-1093 Lamp Man</color>"
s_c_p073_abel_special_introduction: "<color=green>SCP-073 Abel</color>"
s_c_p073_cain_special_introduction: "<color=green>SCP-073 Cain</color>"
s_c_p191_special_introduction: "<color=red>SCP-191 Mechanical Girl</color>"
s_c_p2936_special_introduction: "<color=red>SCP-2936-1 Giant German Robot</color>"
# Special MTF descriptions
skynet_special_introduction: "<color=blue>MTF Skynet</color>"
see_no_evil_special_introduction: "<color=blue>MTF Eta-10</color>"
